### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by hiimbex**
making some changes!!

### CODE REVIEW

**Comment by gkranis** [comment]
Thanks for opening this issue!

**Comment by gkranis** [comment]
Thanks for opening this issue!

**Comment by mathieubergeron** [comment]
Thanks for opening this issue!

**Comment by mathieubergeron** [comment]
Thanks for opening this issue!

**Comment by mathieubergeron** [comment]
Thanks for opening this issue!

**Comment by mathieubergeron** [comment]
Thanks for opening this issue!

**Comment by mathieubergeron** [comment]
Thanks for opening this issue!aa

**Comment by mathieubergeron** [comment]
Thanks for opening this issue!aa

**Comment by mathieubergeron** [comment]
Thanks for opening this issue!aa

**Comment by mathieubergeron** [comment]
Thanks for opening this issue!aa

**Comment by mathieubergeron** [comment]
Thanks for opening this issue!aa

**Comment by mathieubergeron** [comment]
Thanks for opening this issue!aa

**Comment by mathieubergeron** [comment]
Thanks for opening this issue!aa

**Comment by mathieubergeron** [comment]
Thanks for opening this issue!aa

**Comment by mathieubergeron** [comment]
Thanks for opening this issue!aa

**Comment by mathieubergeron** [comment]
Thanks for opening this issue!aa

**Comment by mathieubergeron** [comment]
Thanks for opening this issue!aa

**Comment by mathieubergeron** [comment]
Thanks for opening this issue!aa

**Pull request merged**
